# Generated by Django 5.2 on 2025-04-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название услуги')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('category', models.CharField(choices=[('children_5_7', 'Для детей 5-7 классов'), ('teens_8_11', 'Для подростков 8-11'), ('school_8_11', 'Для школьников 8-11 классов'), ('adults', 'Для взрослых')], max_length=20, verbose_name='Категория')),
                ('subtitle', models.CharField(max_length=200, verbose_name='Что дает программа?')),
                ('benefits_list', models.TextField(verbose_name='Что дает программа?')),
                ('image', models.FileField(upload_to='programs/', verbose_name='Баннер программы')),
            ],
        ),
    ]
