# Generated by Django 5.2 on 2025-04-28 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('status', models.CharField(choices=[('sent', 'Отправлено'), ('confirmed', 'Подтверждено'), ('paid', 'Оплачено'), ('canceled', 'Отменено')], default='sent', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_service.program')),
            ],
        ),
    ]
