# Generated by Django 5.2 on 2025-04-29 01:28

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_service', '0002_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='subtitle',
        ),
        migrations.AlterField(
            model_name='program',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('children_5_7', 'Для детей 5-7 классов'), ('school_8_11', 'Для школьников 8-11 классов'), ('adults', 'Для взрослых'), ('group', 'Групповой тренинг')], max_length=200, verbose_name='Категории'),
        ),
    ]
