# Generated by Django 5.2 on 2025-05-24 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_service', '0005_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата проведения'),
        ),
    ]
