# Generated by Django 5.2 on 2025-05-25 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_service', '0006_program_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='qrcode',
            field=models.FileField(blank=True, null=True, upload_to='programs/qr/', verbose_name='QR-код для оплаты'),
        ),
    ]
