# Generated by Django 5.2 on 2025-05-25 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_service', '0007_program_qrcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='qrcode',
        ),
    ]
